### ISSUE TITLE
Etags are now different from md5 on piston-meta

### ISSUE THREAD

**Issue by coehlrich** [LexManos/MappingToy#5]
Version jsons are now hosted on piston-meta.mojang.com which returns etags in the format of `0x8DA4EEC2E45F8BE` (22w24a's etag) which isn't the md5 hash (for 1.19 the etag is `0x8DA4EEC2EEE2DE0`).

**Comment by LexManos** [comment]
Ya.. unfortunately that means that we wont be able o validate the download didn't get corrupted.
Technically an ETag is just any string so we'd have to store them alongside the file itself.
